# -*- coding: utf-8 -*-
"""task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k1a_TaEjobj7DKepZI-zxk-iNtlzLO6j

#**Data Visualization**

installing libraries and packages:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

"""uploading dataset file:"""

df = pd.read_csv('/content/latestdata.csv')
df

"""all NaN values in each columns:"""

df.isnull().sum()

"""in the code below we have to drop many columns of 'df', because it has got lots of missing values (NaN) and some have useless information:"""

df2 = df.drop(columns=['ID','age','sex','city','date_onset_symptoms','date_admission_hospital','symptoms','lives_in_Wuhan','travel_history_dates',
         'travel_history_location','reported_market_exposure','additional_information','chronic_disease','source','sequence_available','outcome',
         'date_death_or_discharge','notes_for_discussion','location','admin3','admin2','admin1','country_new','data_moderator_initials'
])
df2

"""calculating NaN values again:"""

df2.isnull().sum()

"""now we can just drop rows that contains NaN values:"""

df2.dropna(inplace=True)
print(f'Null values:\n{df2.isnull().sum()}')
print('='*27)
print(f'df2 shape: {df2.shape}')

df2

"""setting 'country' column to index makes table more prettier:"""

df3 = df2.set_index('country')
df3

"""grouping columns makes more easier to understand the table:"""

df4 = df3.groupby(['country','province']).max()
df4

"""and now we can show the result with vizual plot (barplot):"""

plt.figure(figsize=(20,12))
sns.barplot(x=df3.index, y=df3['admin_id'])

plt.title('COVID-19 Infected Person List')
plt.xlabel('Country')
plt.xticks(rotation=90)
plt.ylabel('People')
plt.grid()

df3.to_csv('task_2.csv')